-- Add 20 more lost items with varied descriptions and brands
INSERT INTO lost_items (item_name, description, category, date_lost, location, campus, contact_name, contact_email, contact_phone, additional_info) VALUES
('Apple AirPods Pro 2nd Gen', 'White charging case with USB-C port. Left earbud has a small scratch. Last used in the library study room.', 'Electronics', '2025-12-18', 'Main Library - 3rd Floor Study Room', 'North Campus', 'Michael Chen', 'mchen@campus.edu', '555-0123', 'Reward offered for return'),
('Samsung Galaxy Buds2 Pro', 'Graphite color wireless earbuds in purple case. Contains my initials "JD" on the case.', 'Electronics', '2025-12-19', 'Student Union - Food Court', 'Central Campus', 'Jessica Davis', 'jdavis@campus.edu', '555-0124', 'Very sentimental value'),
('Sony WH-1000XM5 Headphones', 'Silver noise-cancelling headphones with black carrying case. Has a "Music Lover" sticker on the right ear cup.', 'Electronics', '2025-12-17', 'Engineering Building - Room 205', 'East Campus', 'Robert Taylor', 'rtaylor@campus.edu', '555-0125', 'Contains custom EQ settings'),
('iPad Pro 12.9 inch M2', 'Space Gray with Magic Keyboard. Has a clear case with floral design. Screen protector installed.', 'Electronics', '2025-12-16', 'Business School - Lecture Hall B', 'South Campus', 'Amanda White', 'awhite@campus.edu', '555-0126', 'Contains important class notes'),
('Microsoft Surface Pro 9', 'Platinum color with Type Cover keyboard. Has university stickers on the back.', 'Electronics', '2025-12-20', 'Computer Lab - Building C', 'West Campus', 'David Martinez', 'dmartinez@campus.edu', '555-0127', 'Urgent - thesis work inside'),
('Coach Leather Wallet', 'Brown leather bifold wallet with gold hardware. Contains student ID and credit cards.', 'Wallet', '2025-12-19', 'Gym - Locker Room', 'North Campus', 'Sarah Johnson', 'sjohnson@campus.edu', '555-0128', 'Please contact immediately'),
('Gucci Card Holder', 'Black leather card holder with GG logo. Contains 3 credit cards and drivers license.', 'Wallet', '2025-12-18', 'Campus Bookstore', 'Central Campus', 'James Wilson', 'jwilson@campus.edu', '555-0129', 'Reward available'),
('Louis Vuitton Wallet', 'Monogram canvas wallet with red interior. Has my initials "EL" embossed.', 'Wallet', '2025-12-17', 'Art Building - Studio 4', 'East Campus', 'Emma Lopez', 'elopez@campus.edu', '555-0130', 'Family heirloom'),
('North Face Backpack', 'Black Borealis backpack with orange accents. Contains laptop sleeve and water bottle holder.', 'Bag', '2025-12-20', 'Bus Stop - Main Entrance', 'South Campus', 'Chris Anderson', 'canderson@campus.edu', '555-0131', 'Has keychain with name tag'),
('Herschel Supply Co. Bag', 'Navy blue Little America backpack with brown leather straps. Contains textbooks.', 'Bag', '2025-12-19', 'Science Building - Lab 301', 'West Campus', 'Olivia Thomas', 'othomas@campus.edu', '555-0132', 'Textbooks are marked with my name'),
('Fjällräven Kånken Backpack', 'Yellow classic Kånken with brown leather handles. Has pins and patches on front.', 'Bag', '2025-12-18', 'Student Center - 2nd Floor', 'North Campus', 'Daniel Garcia', 'dgarcia@campus.edu', '555-0133', 'Very distinctive with custom patches'),
('Tumi Briefcase', 'Black ballistic nylon briefcase with laptop compartment. Contains work documents.', 'Bag', '2025-12-17', 'Administration Building - Conference Room', 'Central Campus', 'Michelle Lee', 'mlee@campus.edu', '555-0134', 'Important documents inside'),
('Dorm Room Keys', 'Set of 3 keys on a blue lanyard with university logo. Includes room key, mailbox key, and bike lock key.', 'Keys', '2025-12-20', 'Dining Hall - North Wing', 'East Campus', 'Kevin Brown', 'kbrown@campus.edu', '555-0135', 'Locked out of room'),
('Car Keys - Honda', 'Honda key fob with black rubber cover. Has a small flashlight keychain attached.', 'Keys', '2025-12-19', 'Parking Lot D', 'South Campus', 'Lisa Martinez', 'lmartinez@campus.edu', '555-0136', 'Urgent - need to drive home'),
('Toyota Key Fob', 'Silver Toyota key with remote start. Attached to a red carabiner with gym membership card.', 'Keys', '2025-12-18', 'Recreation Center - Front Desk', 'West Campus', 'Ryan Clark', 'rclark@campus.edu', '555-0137', 'Spare key at home'),
('Calculus Textbook', 'Stewart Calculus 9th Edition. Hardcover with yellow and blue cover. Name written inside front cover.', 'Books', '2025-12-17', 'Math Building - Room 115', 'North Campus', 'Ashley Rodriguez', 'arodriguez@campus.edu', '555-0138', 'Needed for final exam'),
('Biology Lab Manual', 'Custom printed lab manual with spiral binding. Has coffee stain on page 45.', 'Books', '2025-12-20', 'Biology Lab - Station 12', 'Central Campus', 'Brandon Lewis', 'blewis@campus.edu', '555-0139', 'Contains all my lab notes'),
('Pandora Charm Bracelet', 'Silver bracelet with 8 charms including a graduation cap and heart. Very sentimental.', 'Jewelry', '2025-12-19', 'Theater Building - Auditorium', 'East Campus', 'Sophia Walker', 'swalker@campus.edu', '555-0140', 'Gift from grandmother'),
('Tiffany & Co. Necklace', 'Silver heart pendant necklace in blue Tiffany box. Engraved with initials "MH".', 'Jewelry', '2025-12-18', 'Music Building - Practice Room 7', 'South Campus', 'Madison Hall', 'mhall@campus.edu', '555-0141', 'Anniversary gift'),
('Passport and Documents', 'US Passport in navy blue cover with international student documents. Name: Alex Kim.', 'Documents', '2025-12-17', 'International Student Office', 'West Campus', 'Alex Kim', 'akim@campus.edu', '555-0142', 'Extremely urgent - travel soon');

-- Add 20 more found items
INSERT INTO found_items (item_name, description, category, date_found, location, campus, contact_name, contact_email, contact_phone, additional_info) VALUES
('Beats Studio Pro Headphones', 'Black wireless headphones with carrying case. Found on bench outside library.', 'Electronics', '2025-12-20', 'Library - Outside Bench Area', 'North Campus', 'Tom Harris', 'tharris@campus.edu', '555-0201', 'Turned in to lost and found'),
('Kindle Paperwhite', 'Black e-reader with leather cover. Has several books downloaded. Found in study room.', 'Electronics', '2025-12-19', 'Library - Study Room 4B', 'Central Campus', 'Rachel Green', 'rgreen@campus.edu', '555-0202', 'Battery was dead when found'),
('GoPro Hero 11', 'Black action camera with waterproof case and accessories. Found near pool.', 'Electronics', '2025-12-18', 'Aquatic Center - Pool Deck', 'East Campus', 'Mark Thompson', 'mthompson@campus.edu', '555-0203', 'Memory card still inside'),
('Nintendo Switch', 'Red and blue Joy-Cons with carrying case. Found in student lounge.', 'Electronics', '2025-12-17', 'Student Union - Gaming Lounge', 'South Campus', 'Jennifer Lee', 'jlee@campus.edu', '555-0204', 'Has game cartridge inside'),
('Fossil Smart Watch', 'Rose gold smartwatch with brown leather band. Found in bathroom.', 'Electronics', '2025-12-20', 'Science Building - 2nd Floor Restroom', 'West Campus', 'Paul Martinez', 'pmartinez@campus.edu', '555-0205', 'Still charged and working'),
('Kate Spade Wallet', 'Pink leather wallet with bow detail. Contains cash and cards. Found on sidewalk.', 'Wallet', '2025-12-19', 'Main Walkway - Near Fountain', 'North Campus', 'Monica Davis', 'mdavis@campus.edu', '555-0206', 'Cash and cards secured'),
('Prada Card Case', 'Black saffiano leather card case. Found in lecture hall under seat.', 'Wallet', '2025-12-18', 'Lecture Hall A - Row 5', 'Central Campus', 'Steven Wilson', 'swilson@campus.edu', '555-0207', 'Multiple cards inside'),
('Burberry Wallet', 'Tan check pattern wallet with leather trim. Found in cafeteria.', 'Wallet', '2025-12-17', 'Dining Hall - Table 23', 'East Campus', 'Laura Anderson', 'landerson@campus.edu', '555-0208', 'ID inside to identify owner'),
('JanSport Backpack', 'Red backpack with laptop and notebooks inside. Found in classroom.', 'Bag', '2025-12-20', 'History Building - Room 302', 'South Campus', 'Eric Thomas', 'ethomas@campus.edu', '555-0209', 'Contains student work'),
('Adidas Gym Bag', 'Black duffel bag with white stripes. Contains workout clothes and shoes.', 'Bag', '2025-12-19', 'Fitness Center - Locker Area', 'West Campus', 'Nicole Garcia', 'ngarcia@campus.edu', '555-0210', 'Gym membership card inside'),
('Longchamp Tote Bag', 'Navy blue Le Pliage tote with brown handles. Contains planner and cosmetics.', 'Bag', '2025-12-18', 'Campus Store - Checkout Area', 'North Campus', 'Andrew Martinez', 'amartinez@campus.edu', '555-0211', 'Planner has name inside'),
('Osprey Hiking Backpack', 'Green 30L backpack with hydration system. Found on trail.', 'Bag', '2025-12-17', 'Campus Trail - Near Parking', 'Central Campus', 'Samantha Brown', 'sbrown@campus.edu', '555-0212', 'Hiking gear inside'),
('BMW Key Fob', 'Black BMW key with comfort access. Found in parking lot.', 'Keys', '2025-12-20', 'Parking Structure B - Level 3', 'East Campus', 'Jason Clark', 'jclark@campus.edu', '555-0213', 'Turned in to security'),
('Apartment Keys', 'Set of keys on a green lanyard. Includes apartment key and mailbox key.', 'Keys', '2025-12-19', 'Bus Stop - South Entrance', 'South Campus', 'Melissa Rodriguez', 'mrodriguez@campus.edu', '555-0214', 'Address tag attached'),
('Bike Lock Key', 'Small key on a yellow keychain. Found near bike racks.', 'Keys', '2025-12-18', 'Bike Rack Area - Building E', 'West Campus', 'Timothy Lewis', 'tlewis@campus.edu', '555-0215', 'Kryptonite brand'),
('Physics Textbook', 'University Physics 15th Edition. Hardcover with notes inside.', 'Books', '2025-12-17', 'Physics Building - Lecture Hall', 'North Campus', 'Christina Walker', 'cwalker@campus.edu', '555-0216', 'Heavily annotated'),
('Chemistry Lab Notebook', 'Black composition notebook with lab data. Name on cover.', 'Books', '2025-12-20', 'Chemistry Lab - Bench 8', 'Central Campus', 'Gregory Hall', 'ghall@campus.edu', '555-0217', 'Full semester of work'),
('Ray-Ban Sunglasses', 'Black Wayfarer sunglasses in brown case. Found on outdoor table.', 'Personal Items', '2025-12-19', 'Outdoor Seating - Quad Area', 'East Campus', 'Victoria Allen', 'vallen@campus.edu', '555-0218', 'Prescription lenses'),
('Cartier Watch', 'Silver watch with blue face and leather strap. Found in restroom.', 'Jewelry', '2025-12-18', 'Student Center - Restroom', 'South Campus', 'Nathan Young', 'nyoung@campus.edu', '555-0219', 'Appears valuable'),
('Medical Alert Bracelet', 'Stainless steel bracelet with medical information. Found in gym.', 'Jewelry', '2025-12-17', 'Gym - Weight Room', 'West Campus', 'Rebecca King', 'rking@campus.edu', '555-0220', 'Medical information engraved');

-- Add 5 more returned items for history
INSERT INTO returned_items (item_name, description, category, return_date, location, campus, owner_name, owner_contact, finder_name, finder_contact, story) VALUES
('MacBook Pro 16-inch M3', 'Space Gray laptop with university stickers. Found in library study room and returned same day.', 'Electronics', '2025-12-15', 'Main Library - Study Room 3A', 'North Campus', 'Tyler Johnson', 'tjohnson@campus.edu', 'Grace Martinez', 'gmartinez@campus.edu', 'Found the laptop left on a desk after closing time. Checked the stickers and recognized the owner from class. Contacted them immediately and met up to return it. They were so relieved!'),
('Vera Bradley Wallet', 'Floral pattern wallet with all cards and cash intact. Returned within hours of being lost.', 'Wallet', '2025-12-14', 'Campus Bookstore - Checkout Counter', 'Central Campus', 'Hannah Wilson', 'hwilson@campus.edu', 'Marcus Thompson', 'mthompson@campus.edu', 'Saw someone drop their wallet while leaving the bookstore. Ran after them but they were too far. Turned it into the bookstore staff who contacted the owner. Happy ending!'),
('Patagonia Backpack', 'Black backpack with laptop and textbooks. Owner was frantically searching for it.', 'Bag', '2025-12-13', 'Student Union - Cafeteria', 'East Campus', 'Zoe Anderson', 'zanderson@campus.edu', 'Lucas Garcia', 'lgarcia@campus.edu', 'Found the backpack under a table. Checked inside for ID and found a student card. Posted on social media and the owner responded within 30 minutes. Met up and returned everything safely.'),
('Rolex Submariner Watch', 'Expensive watch found in gym locker room. Owner was incredibly grateful.', 'Jewelry', '2025-12-12', 'Recreation Center - Locker Room', 'South Campus', 'Ethan Davis', 'edavis@campus.edu', 'Ava Rodriguez', 'arodriguez@campus.edu', 'Found this watch on the bench in the locker room. Knew it was valuable so immediately turned it in to the front desk. Owner came looking for it the next day. They were so happy they offered a reward, but I declined. Just happy to help!'),
('Prescription Glasses', 'Black frame glasses in hard case. Returned to very grateful owner who could not see without them.', 'Personal Items', '2025-12-11', 'Library - Computer Lab', 'West Campus', 'Chloe Martinez', 'cmartinez@campus.edu', 'Noah Thompson', 'nthompson@campus.edu', 'Found these glasses on a computer desk. Posted in our class group chat and the owner responded immediately. They had been looking everywhere! Met up within 10 minutes to return them. They were so relieved they could see again for their exam the next day.');